; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
;--------------- select you board --------------;
; default_envs = T3_S3_V1_2_LR1121
; default_envs = esp32-s2-kaluga-1
default_envs = esp32dev

;--------------- select a example --------------;
; CC1101
; src_dir = examples/CC1101_recv
; src_dir = examples/CC1101_send

; LR1121
src_dir = examples/LR1121_recv
; src_dir = examples/LR1121_send

; NRF24
; src_dir = examples/NRF24_recv_1
; src_dir = examples/NRF24_send_1

; src_dir = examples/NRF24_send_2

; 原形屏幕程序
; src_dir = examples/rf_NRF24_recv

; src_dir = examples/rf_test
; src_dir = examples/ST25R3916_test
; src_dir = examples/rf24_test
; src_dir = examples/NFC

[env]
;--------------- board config --------------;
platform = espressif32@6.5.0
framework = arduino
upload_speed =  921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[esp32s3_base]
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DCORE_DEBUG_LEVEL=4

[env:T3_S3_V1_2_LR1121]
extends = env
boards_dir = boards
board = t3_s3_v1_x
build_flags = ${esp32s3_base.build_flags}
    -DT3_S3_V1_2_LR1121


[env:esp32-s2-kaluga-1]
board = esp32-s2-kaluga-1

build_flags = 
    -DESP32S2=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT

    -DCORE_DEBUG_LEVEL=3

    -DRADIOLIB_LOW_LEVEL=1
    ; -DBOARD_HAS_PSRAM=1
    ; -mfix-esp32-psram-cache-issue

    -DDISABLE_ALL_LIBRARY_WARNINGS

lib_deps =
    ; jgromes/RadioLib@^7.1.2


[env:esp32dev]
board = esp32dev

build_flags = 
    -DESP32=1
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    -UARDUINO_USB_CDC_ON_BOOT

    -DCORE_DEBUG_LEVEL=3

    -DRADIOLIB_LOW_LEVEL=1

    ; -DBOARD_HAS_PSRAM=1
    ; -mfix-esp32-psram-cache-issue

    -DDISABLE_ALL_LIBRARY_WARNINGS

lib_deps =
    ; jgromes/RadioLib@^7.1.2